image:
  repositoryImage: morganmwjacrdevelopment.azurecr.io/fireflyapi
  tag: latest
service:
  type: LoadBalancer          # NodePort/ClinetIP/LoadBalancer
  port: 80                 # The port to expose on the service
  targetPort: 80           # The port your application listens on
config:
  myTestKey: "This is my value in case we need to add config later"
  anotherKey: "Another value example"