apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}-container
        image: {{ .Values.image.repositoryImage }}:{{ .Values.image.tag }} # Your ACR image URL
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.service.targetPort }}  # The internal port exposed by docker container
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"  # Example environment variable, adjust as needed
        - name: ConnectionStrings__SqlServerDatabase
          valueFrom:
            secretKeyRef:
              name: sql-server-connection-string-secret
              key: connectionString
        readinessProbe:
          httpGet:
            path: /health/ready # Endpoint checks all service dependencies are up
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live # Endpoint just returns 200 OK if it can to check live
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: 15
          periodSeconds: 20
      imagePullSecrets:
      - name: acr-secret  # acr password stored in aks secret