name: Release to AKS

on:
  push:
    branches:
      - sqlserver-docker-and-testcontainer
  #workflow_dispatch:  # This allows the workflow to be triggered manually

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/fireflyapi:${{ github.sha }} .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/fireflyapi:${{ github.sha }}

      - name: Azure AKS set context
        uses: azure/aks-set-context@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

      # - name: Deploy to AKS
      #   run: |
      #     kubectl set image deployment/myapp-deployment fireflyapi=${{ secrets.ACR_LOGIN_SERVER }}/fireflyapi:${{ github.sha }}
      #     kubectl rollout status deployment/myapp-deployment
